version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "user-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jrcdngfn8k8u"
s3_prefix = "user-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
